### ISSUE TITLE
install via brew cask

### ISSUE THREAD

**Issue by joaocc** [syncthing/syncthing-mac#4]
Hi,
Is there any formula to install this via homebrew cask?
Thx

**Comment by canton7** [comment]
This particular project is over 2 years old and only has a single commit - you probably don't want to install it!

There's a homebrew package for syncthing [here](http://brewformulas.org/Syncthing), and some GUI wrappers [here](https://docs.syncthing.net/users/contrib.html#cross-platform) and [here](https://docs.syncthing.net/users/contrib.html#os-x).

**Comment by calmh** [comment]
Index. I just haven't bothered deleting it yet.
